//Teste de Requisições REST - filmes
@baseURL = http://localhost:4000
@id = 
###
// GET - Lista todos os filmes
GET {{baseURL}}/filmes
Content-Type: application/json

###
// GET - Lista apenas um filme pelo id
GET {{baseURL}}/filmes/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo filme
POST {{baseURL}}/filmes
Content-Type: application/json

{
   "nome":"",
   "anoLancamento":,
   "diretor":"",
   "genero":"",
   "notaIMDB":
}

### 
// DELETE - Apaga um filme através do id informado
DELETE {{baseURL}}/filmes/{{id}}
Content-Type: application/json

###
// PUT - Altera um filme pelo ID
PUT {{baseURL}}/filmes/
Content-Type: application/json

{
    "_id": "", 
    "nome":"",
   "anoLancamento":,
   "diretor":"",
   "genero":"",
   "notaIMDB":
}


